version: 0.0
os: linux
files:
  - source: ./
    destination: /var/www/html
hooks:
  AfterInstall:
    - location: afterinstall.sh
      timeout: 30
  ApplicationStart:
    - location: applicationstart.sh
      timeout: 30
